FROM jenkins/jenkins:lts

USER root

# Install Python and virtualenv
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install pandas && \
    apt-get clean

# DO NOT override Jenkins PATH
# ENV PATH="/opt/venv/bin:$PATH"   <-- remove this

USER jenkins

# Optional: expose explicitly
EXPOSE 8080

